URL=http://127.0.0.1:4723
DEVICE=Android
UDID=9b010059305331323800d45b3428c0
PACKAGE=com.valuenable.las.dev
ACTIVITY=com.valuenable.las.MainActivity

# ===================================================================
# EXECUTION SWITCH ENGINE
# Options: 
#   1. LOCAL_REAL        - Executes tests on your connected physical phone.
#   2. LOCAL_EMULATOR    - Executes tests on a free local Android Emulator.
#   3. CLOUD_BROWSERSTACK - Executes tests in the Cloud on BrowserStack.
# ===================================================================
RUN_MODE=LOCAL_EMULATOR

# ===================================================================
# BROWSERSTACK CLOUD INTEGRATION DETAILS
# ===================================================================
BROWSERSTACK_URL=http://hub.browserstack.com/wd/hub
BROWSERSTACK_USERNAME=your_browserstack_username
BROWSERSTACK_ACCESS_KEY=your_browserstack_access_key
BROWSERSTACK_APP_URL=bs://uploaded_app_hash_id
